### ISSUE TITLE
Unexecuted-Changes Descriptions

### ISSUE THREAD

**Issue by Carfilm** [Carfilm/Unexecuted-Changes#1]
Home Page: 
The image looks murky, without contrast, the blacks are not black. The other images do not have that problem. Please correct.

Mission Page: 
There needs to be an accordion after "...into the passionate", that hides "Value Statement ""Vision Statement."

Team Page: 
The green thin sliver image does not reach across the window.
The red footer shows black underneath and does not reach across on the left.
Alexander Davidis:
Video on the top right has wrong naming and shows no thumb nail.
Paul Babbs:
pictures have to be switched. The one with the car in the background on the overview, the close up inside the bio.  
Joe DeSalvo:
Videos are labeled wrong:
Top left: Freight Rail Works: Joe DeSalvo, Director, Director of Photography, Editor
Top right: Casino Game Nights: Joe DeSalvo, Director of Photography
Botom left: Jaguar XJ: Joe DeSalvo, Director of Photography
Bottom right: Mercedes Benz S Class: Joe DeSalvo, Director of Photography
Thumbnails are all wrong
Christopher Rutkowski:
All videos need proper Thumbnails
Stefan Pfeil:
Bottom left video needs proper thumb nail
Bradley Farrell:
has to be deleted. 
Paul Mei:
needs a picture and Bio. I sent those by email to you. 

Film Page:
Is missing amy thumbnails

About Page:
The red footer shows black underneath and does not reach across on the left.

Contact Page:
Email link does not work

Disclamer Page:
After the first sentence that ends on "Condition and Service" should be a paragraph and after that paragraph should be an accordion so that one can see the footer right away.

Navigation Bar:
The button for the selected page needs to stay red so that one knows where this is. 

Mobile Devise Usability. 
Neither page nor copy text can be re-sized so it is unusable since unreadable.

**Comment by mrrorinc** [comment]
this is duplicate, please remove
