### ISSUE TITLE
Disclaimer Page:

### ISSUE THREAD

**Issue by Carfilm** [Carfilm/Unexecuted-Changes#21]
After the first sentence that ends on "Condition and Service" should be a paragraph and after that paragraph should be an accordion so that one can see the footer right away, so it is easier to navigate.

**Comment by mrrorinc** [comment]
RESOLVED

**Comment by Carfilm** [comment]
The text is now funky formatted, to the right with headline to the left??

**Comment by mrrorinc** [comment]
RESOLVED, updated on server
