### ISSUE TITLE
Mission Page:

### ISSUE THREAD

**Issue by Carfilm** [Carfilm/Unexecuted-Changes#3]
There needs to be an accordion after "...into the passionate", that hides "Value Statement ""Vision Statement." ..but not the picture below, just as on all other pages.

**Comment by mrrorinc** [comment]
RESOLVED

**Comment by Carfilm** [comment]
now there is black under the footer and it does not reach across on the left

**Comment by mrrorinc** [comment]
this is now FIXED, updated on server, RESOLVED.

**Comment by Carfilm** [comment]
Let me know when it is life
